### ISSUE TITLE
Matplotlib code is missing plt.show()

### ISSUE THREAD

**Issue by banjaxedben** [murrayrm/fbs2e-python#1]
Thank you for the amazing resources you have created: the book, python-control, and this example Python code!

Not being a matplotlib expert, I struggled initially with the first example (figure-1.11-cruise_robustness.py), as the script ran without errors but did not produce any visible output.
I eventually realised I just needed to add the line:
`plt.show()`

Your original development environment is probably Spyder, iPython, Jupyter, or some other shell where matplotlib automatically runs in interactive mode (%matplotlib auto), and therefore you didn't need `plt.show()`.
In my case, I am running the examples in a terminal in VS Code, and `plt.show()` is needed.
I suggest that the README be expanded to explain this?

**Comment by murrayrm** [comment]
Fixed in 4ebb8fa710a55f158d31f1702afe8816d6a3b11d.
